project_id = "lwqfurkfjkilsnjtmemj"

[functions.analyze-image-search-intent]
verify_jwt = true

[functions.generate-final-medical-analysis]
verify_jwt = true

[functions.grok-chat]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.generate-diagnosis]
verify_jwt = true

[functions.patient-report-agent]
verify_jwt = true

[functions.clear-form-memory]
verify_jwt = true

[functions.medical-image-search]
verify_jwt = true

[functions.validate-alpha-code]
verify_jwt = false

[functions.fetch-health-alerts]
verify_jwt = true